import type { Metadata } from "next";
import { connection } from "next/server";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import { readServerRuntimeConfig, serializeRuntimeConfig } from "@/lib/runtimeConfig";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Opts into dynamic rendering, so process.env is read per request inside the
  // running container instead of being frozen in at `next build`. This is what
  // lets the ECS task definition set the API URLs.
  await connection();
  const runtimeConfig = readServerRuntimeConfig();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* First thing in the body, so window.__ENV exists before any bundle runs */}
        <script
          id="runtime-config"
          dangerouslySetInnerHTML={{ __html: serializeRuntimeConfig(runtimeConfig) }}
        />
        <AuthProvider>

        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
